"""Game Configuration and Constants"""

# Screen Settings
SCREEN_WIDTH = 1080
SCREEN_HEIGHT = 1920
FPS = 60

# Colors
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 100, 255)
COLOR_YELLOW = (255, 255, 0)
COLOR_GRAY = (128, 128, 128)
COLOR_DARK_GREEN = (34, 139, 34)
COLOR_TOXIC_GREEN = (50, 200, 50)

# Game States
GAME_STATE_MENU = "menu"
GAME_STATE_RUNNER = "runner"
GAME_STATE_BASE = "base"
GAME_STATE_BATTLE = "battle"
GAME_STATE_PAUSE = "pause"
GAME_STATE_GAMEOVER = "gameover"

# Runner Mode Settings
RUNNER_SPEED = 8
LANE_WIDTH = SCREEN_WIDTH // 3
NUM_LANES = 3
ENEMY_SPEED = 5
BOSS_HEALTH = 100

# Player Settings
PLAYER_HEALTH = 100
PLAYER_ATTACK = 10
PLAYER_DEFENSE = 5
PLAYER_START_SQUAD = 10

# Base Mode Settings
BASE_WIDTH = SCREEN_WIDTH
BASE_HEIGHT = SCREEN_HEIGHT
GRID_SIZE = 50

# Resources
RESOURCE_GOLD = "gold"
RESOURCE_IRON = "iron"
RESOURCE_DIAMOND = "diamond"

START_GOLD = 500
START_IRON = 300
START_DIAMOND = 50

# Building Types
BUILDING_HQ = "hq"
BUILDING_BARRACKS = "barracks"
BUILDING_TAVERN = "tavern"
BUILDING_DEFENSE = "defense"
BUILDING_MINE = "mine"
BUILDING_FARM = "farm"

# Math Gates
BLUE_GATE_BONUS = 10
BLUE_GATE_MULTIPLIER = 2
RED_GATE_PENALTY = -20
RED_GATE_DIVISOR = 2

# Enemy Types
ENEMY_ZOMBIE_SMALL = "zombie_small"
ENEMY_ZOMBIE_BIG = "zombie_big"
ENEMY_BOSS = "boss"

# Game Difficulty
DIFFICULTY_EASY = 1.0
DIFFICULTY_NORMAL = 1.5
DIFFICULTY_HARD = 2.0

# UI
UI_BUTTON_HEIGHT = 60
UI_BUTTON_WIDTH = 150
UI_PADDING = 10
UI_FONT_SIZE_LARGE = 36
UI_FONT_SIZE_MEDIUM = 24
UI_FONT_SIZE_SMALL = 18
